//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CapEvents = newCapEventsTable("", "cap_events", "")

type capEventsTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnInteger
	SessionID    sqlite.ColumnInteger
	Timestamp    sqlite.ColumnTimestamp
	Module       sqlite.ColumnString
	CapRequired  sqlite.ColumnFloat
	CapAvailable sqlite.ColumnFloat

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CapEventsTable struct {
	capEventsTable

	EXCLUDED capEventsTable
}

// AS creates new CapEventsTable with assigned alias
func (a CapEventsTable) AS(alias string) *CapEventsTable {
	return newCapEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CapEventsTable with assigned schema name
func (a CapEventsTable) FromSchema(schemaName string) *CapEventsTable {
	return newCapEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CapEventsTable with assigned table prefix
func (a CapEventsTable) WithPrefix(prefix string) *CapEventsTable {
	return newCapEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CapEventsTable with assigned table suffix
func (a CapEventsTable) WithSuffix(suffix string) *CapEventsTable {
	return newCapEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCapEventsTable(schemaName, tableName, alias string) *CapEventsTable {
	return &CapEventsTable{
		capEventsTable: newCapEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCapEventsTableImpl("", "excluded", ""),
	}
}

func newCapEventsTableImpl(schemaName, tableName, alias string) capEventsTable {
	var (
		IDColumn           = sqlite.IntegerColumn("id")
		SessionIDColumn    = sqlite.IntegerColumn("session_id")
		TimestampColumn    = sqlite.TimestampColumn("timestamp")
		ModuleColumn       = sqlite.StringColumn("module")
		CapRequiredColumn  = sqlite.FloatColumn("cap_required")
		CapAvailableColumn = sqlite.FloatColumn("cap_available")
		allColumns         = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, ModuleColumn, CapRequiredColumn, CapAvailableColumn}
		mutableColumns     = sqlite.ColumnList{SessionIDColumn, TimestampColumn, ModuleColumn, CapRequiredColumn, CapAvailableColumn}
		defaultColumns     = sqlite.ColumnList{}
	)

	return capEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SessionID:    SessionIDColumn,
		Timestamp:    TimestampColumn,
		Module:       ModuleColumn,
		CapRequired:  CapRequiredColumn,
		CapAvailable: CapAvailableColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
