//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Characters = newCharactersTable("", "characters", "")

type charactersTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnInteger
	Name        sqlite.ColumnString
	EveID       sqlite.ColumnInteger
	PortraitURL sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CharactersTable struct {
	charactersTable

	EXCLUDED charactersTable
}

// AS creates new CharactersTable with assigned alias
func (a CharactersTable) AS(alias string) *CharactersTable {
	return newCharactersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CharactersTable with assigned schema name
func (a CharactersTable) FromSchema(schemaName string) *CharactersTable {
	return newCharactersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CharactersTable with assigned table prefix
func (a CharactersTable) WithPrefix(prefix string) *CharactersTable {
	return newCharactersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CharactersTable with assigned table suffix
func (a CharactersTable) WithSuffix(suffix string) *CharactersTable {
	return newCharactersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCharactersTable(schemaName, tableName, alias string) *CharactersTable {
	return &CharactersTable{
		charactersTable: newCharactersTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newCharactersTableImpl("", "excluded", ""),
	}
}

func newCharactersTableImpl(schemaName, tableName, alias string) charactersTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		EveIDColumn       = sqlite.IntegerColumn("eve_id")
		PortraitURLColumn = sqlite.StringColumn("portrait_url")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, EveIDColumn, PortraitURLColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, EveIDColumn, PortraitURLColumn}
		defaultColumns    = sqlite.ColumnList{}
	)

	return charactersTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		EveID:       EveIDColumn,
		PortraitURL: PortraitURLColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
