//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CombatEvents = newCombatEventsTable("", "combat_events", "")

type combatEventsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	SessionID sqlite.ColumnInteger
	Timestamp sqlite.ColumnTimestamp
	Direction sqlite.ColumnString
	Damage    sqlite.ColumnInteger
	Entity    sqlite.ColumnString
	Weapon    sqlite.ColumnString
	HitType   sqlite.ColumnString
	IsMiss    sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CombatEventsTable struct {
	combatEventsTable

	EXCLUDED combatEventsTable
}

// AS creates new CombatEventsTable with assigned alias
func (a CombatEventsTable) AS(alias string) *CombatEventsTable {
	return newCombatEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CombatEventsTable with assigned schema name
func (a CombatEventsTable) FromSchema(schemaName string) *CombatEventsTable {
	return newCombatEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CombatEventsTable with assigned table prefix
func (a CombatEventsTable) WithPrefix(prefix string) *CombatEventsTable {
	return newCombatEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CombatEventsTable with assigned table suffix
func (a CombatEventsTable) WithSuffix(suffix string) *CombatEventsTable {
	return newCombatEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCombatEventsTable(schemaName, tableName, alias string) *CombatEventsTable {
	return &CombatEventsTable{
		combatEventsTable: newCombatEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newCombatEventsTableImpl("", "excluded", ""),
	}
}

func newCombatEventsTableImpl(schemaName, tableName, alias string) combatEventsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		SessionIDColumn = sqlite.IntegerColumn("session_id")
		TimestampColumn = sqlite.TimestampColumn("timestamp")
		DirectionColumn = sqlite.StringColumn("direction")
		DamageColumn    = sqlite.IntegerColumn("damage")
		EntityColumn    = sqlite.StringColumn("entity")
		WeaponColumn    = sqlite.StringColumn("weapon")
		HitTypeColumn   = sqlite.StringColumn("hit_type")
		IsMissColumn    = sqlite.IntegerColumn("is_miss")
		allColumns      = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, DirectionColumn, DamageColumn, EntityColumn, WeaponColumn, HitTypeColumn, IsMissColumn}
		mutableColumns  = sqlite.ColumnList{SessionIDColumn, TimestampColumn, DirectionColumn, DamageColumn, EntityColumn, WeaponColumn, HitTypeColumn, IsMissColumn}
		defaultColumns  = sqlite.ColumnList{DamageColumn, IsMissColumn}
	)

	return combatEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		SessionID: SessionIDColumn,
		Timestamp: TimestampColumn,
		Direction: DirectionColumn,
		Damage:    DamageColumn,
		Entity:    EntityColumn,
		Weapon:    WeaponColumn,
		HitType:   HitTypeColumn,
		IsMiss:    IsMissColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
