//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var KillEvents = newKillEventsTable("", "kill_events", "")

type killEventsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	SessionID sqlite.ColumnInteger
	Timestamp sqlite.ColumnTimestamp
	Entity    sqlite.ColumnString
	BountyIsk sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type KillEventsTable struct {
	killEventsTable

	EXCLUDED killEventsTable
}

// AS creates new KillEventsTable with assigned alias
func (a KillEventsTable) AS(alias string) *KillEventsTable {
	return newKillEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new KillEventsTable with assigned schema name
func (a KillEventsTable) FromSchema(schemaName string) *KillEventsTable {
	return newKillEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new KillEventsTable with assigned table prefix
func (a KillEventsTable) WithPrefix(prefix string) *KillEventsTable {
	return newKillEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new KillEventsTable with assigned table suffix
func (a KillEventsTable) WithSuffix(suffix string) *KillEventsTable {
	return newKillEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newKillEventsTable(schemaName, tableName, alias string) *KillEventsTable {
	return &KillEventsTable{
		killEventsTable: newKillEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newKillEventsTableImpl("", "excluded", ""),
	}
}

func newKillEventsTableImpl(schemaName, tableName, alias string) killEventsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		SessionIDColumn = sqlite.IntegerColumn("session_id")
		TimestampColumn = sqlite.TimestampColumn("timestamp")
		EntityColumn    = sqlite.StringColumn("entity")
		BountyIskColumn = sqlite.IntegerColumn("bounty_isk")
		allColumns      = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, EntityColumn, BountyIskColumn}
		mutableColumns  = sqlite.ColumnList{SessionIDColumn, TimestampColumn, EntityColumn, BountyIskColumn}
		defaultColumns  = sqlite.ColumnList{BountyIskColumn}
	)

	return killEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		SessionID: SessionIDColumn,
		Timestamp: TimestampColumn,
		Entity:    EntityColumn,
		BountyIsk: BountyIskColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
