//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var MiningFullEvents = newMiningFullEventsTable("", "mining_full_events", "")

type miningFullEventsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	SessionID sqlite.ColumnInteger
	Timestamp sqlite.ColumnTimestamp
	Module    sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MiningFullEventsTable struct {
	miningFullEventsTable

	EXCLUDED miningFullEventsTable
}

// AS creates new MiningFullEventsTable with assigned alias
func (a MiningFullEventsTable) AS(alias string) *MiningFullEventsTable {
	return newMiningFullEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MiningFullEventsTable with assigned schema name
func (a MiningFullEventsTable) FromSchema(schemaName string) *MiningFullEventsTable {
	return newMiningFullEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MiningFullEventsTable with assigned table prefix
func (a MiningFullEventsTable) WithPrefix(prefix string) *MiningFullEventsTable {
	return newMiningFullEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MiningFullEventsTable with assigned table suffix
func (a MiningFullEventsTable) WithSuffix(suffix string) *MiningFullEventsTable {
	return newMiningFullEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMiningFullEventsTable(schemaName, tableName, alias string) *MiningFullEventsTable {
	return &MiningFullEventsTable{
		miningFullEventsTable: newMiningFullEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newMiningFullEventsTableImpl("", "excluded", ""),
	}
}

func newMiningFullEventsTableImpl(schemaName, tableName, alias string) miningFullEventsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		SessionIDColumn = sqlite.IntegerColumn("session_id")
		TimestampColumn = sqlite.TimestampColumn("timestamp")
		ModuleColumn    = sqlite.StringColumn("module")
		allColumns      = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, ModuleColumn}
		mutableColumns  = sqlite.ColumnList{SessionIDColumn, TimestampColumn, ModuleColumn}
		defaultColumns  = sqlite.ColumnList{}
	)

	return miningFullEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		SessionID: SessionIDColumn,
		Timestamp: TimestampColumn,
		Module:    ModuleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
