//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var MiningEvents = newMiningEventsTable("", "mining_events", "")

type miningEventsTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnInteger
	SessionID  sqlite.ColumnInteger
	Timestamp  sqlite.ColumnTimestamp
	OreType    sqlite.ColumnString
	Amount     sqlite.ColumnInteger
	IsResidue  sqlite.ColumnInteger
	IsCritical sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MiningEventsTable struct {
	miningEventsTable

	EXCLUDED miningEventsTable
}

// AS creates new MiningEventsTable with assigned alias
func (a MiningEventsTable) AS(alias string) *MiningEventsTable {
	return newMiningEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MiningEventsTable with assigned schema name
func (a MiningEventsTable) FromSchema(schemaName string) *MiningEventsTable {
	return newMiningEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MiningEventsTable with assigned table prefix
func (a MiningEventsTable) WithPrefix(prefix string) *MiningEventsTable {
	return newMiningEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MiningEventsTable with assigned table suffix
func (a MiningEventsTable) WithSuffix(suffix string) *MiningEventsTable {
	return newMiningEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMiningEventsTable(schemaName, tableName, alias string) *MiningEventsTable {
	return &MiningEventsTable{
		miningEventsTable: newMiningEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newMiningEventsTableImpl("", "excluded", ""),
	}
}

func newMiningEventsTableImpl(schemaName, tableName, alias string) miningEventsTable {
	var (
		IDColumn         = sqlite.IntegerColumn("id")
		SessionIDColumn  = sqlite.IntegerColumn("session_id")
		TimestampColumn  = sqlite.TimestampColumn("timestamp")
		OreTypeColumn    = sqlite.StringColumn("ore_type")
		AmountColumn     = sqlite.IntegerColumn("amount")
		IsResidueColumn  = sqlite.IntegerColumn("is_residue")
		IsCriticalColumn = sqlite.IntegerColumn("is_critical")
		allColumns       = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, OreTypeColumn, AmountColumn, IsResidueColumn, IsCriticalColumn}
		mutableColumns   = sqlite.ColumnList{SessionIDColumn, TimestampColumn, OreTypeColumn, AmountColumn, IsResidueColumn, IsCriticalColumn}
		defaultColumns   = sqlite.ColumnList{AmountColumn, IsResidueColumn, IsCriticalColumn}
	)

	return miningEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		SessionID:  SessionIDColumn,
		Timestamp:  TimestampColumn,
		OreType:    OreTypeColumn,
		Amount:     AmountColumn,
		IsResidue:  IsResidueColumn,
		IsCritical: IsCriticalColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
