//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ReloadEvents = newReloadEventsTable("", "reload_events", "")

type reloadEventsTable struct {
	sqlite.Table

	// Columns
	ID              sqlite.ColumnInteger
	SessionID       sqlite.ColumnInteger
	Timestamp       sqlite.ColumnTimestamp
	Charge          sqlite.ColumnString
	Launcher        sqlite.ColumnString
	DurationSeconds sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ReloadEventsTable struct {
	reloadEventsTable

	EXCLUDED reloadEventsTable
}

// AS creates new ReloadEventsTable with assigned alias
func (a ReloadEventsTable) AS(alias string) *ReloadEventsTable {
	return newReloadEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReloadEventsTable with assigned schema name
func (a ReloadEventsTable) FromSchema(schemaName string) *ReloadEventsTable {
	return newReloadEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReloadEventsTable with assigned table prefix
func (a ReloadEventsTable) WithPrefix(prefix string) *ReloadEventsTable {
	return newReloadEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReloadEventsTable with assigned table suffix
func (a ReloadEventsTable) WithSuffix(suffix string) *ReloadEventsTable {
	return newReloadEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReloadEventsTable(schemaName, tableName, alias string) *ReloadEventsTable {
	return &ReloadEventsTable{
		reloadEventsTable: newReloadEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newReloadEventsTableImpl("", "excluded", ""),
	}
}

func newReloadEventsTableImpl(schemaName, tableName, alias string) reloadEventsTable {
	var (
		IDColumn              = sqlite.IntegerColumn("id")
		SessionIDColumn       = sqlite.IntegerColumn("session_id")
		TimestampColumn       = sqlite.TimestampColumn("timestamp")
		ChargeColumn          = sqlite.StringColumn("charge")
		LauncherColumn        = sqlite.StringColumn("launcher")
		DurationSecondsColumn = sqlite.IntegerColumn("duration_seconds")
		allColumns            = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, ChargeColumn, LauncherColumn, DurationSecondsColumn}
		mutableColumns        = sqlite.ColumnList{SessionIDColumn, TimestampColumn, ChargeColumn, LauncherColumn, DurationSecondsColumn}
		defaultColumns        = sqlite.ColumnList{}
	)

	return reloadEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		SessionID:       SessionIDColumn,
		Timestamp:       TimestampColumn,
		Charge:          ChargeColumn,
		Launcher:        LauncherColumn,
		DurationSeconds: DurationSecondsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
