//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Sessions = newSessionsTable("", "sessions", "")

type sessionsTable struct {
	sqlite.Table

	// Columns
	ID             sqlite.ColumnInteger
	CharacterID    sqlite.ColumnInteger
	SessionKey     sqlite.ColumnString
	LogPath        sqlite.ColumnString
	StartedAt      sqlite.ColumnTimestamp
	Language       sqlite.ColumnString
	LastByteOffset sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type SessionsTable struct {
	sessionsTable

	EXCLUDED sessionsTable
}

// AS creates new SessionsTable with assigned alias
func (a SessionsTable) AS(alias string) *SessionsTable {
	return newSessionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SessionsTable with assigned schema name
func (a SessionsTable) FromSchema(schemaName string) *SessionsTable {
	return newSessionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SessionsTable with assigned table prefix
func (a SessionsTable) WithPrefix(prefix string) *SessionsTable {
	return newSessionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SessionsTable with assigned table suffix
func (a SessionsTable) WithSuffix(suffix string) *SessionsTable {
	return newSessionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSessionsTable(schemaName, tableName, alias string) *SessionsTable {
	return &SessionsTable{
		sessionsTable: newSessionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newSessionsTableImpl("", "excluded", ""),
	}
}

func newSessionsTableImpl(schemaName, tableName, alias string) sessionsTable {
	var (
		IDColumn             = sqlite.IntegerColumn("id")
		CharacterIDColumn    = sqlite.IntegerColumn("character_id")
		SessionKeyColumn     = sqlite.StringColumn("session_key")
		LogPathColumn        = sqlite.StringColumn("log_path")
		StartedAtColumn      = sqlite.TimestampColumn("started_at")
		LanguageColumn       = sqlite.StringColumn("language")
		LastByteOffsetColumn = sqlite.IntegerColumn("last_byte_offset")
		allColumns           = sqlite.ColumnList{IDColumn, CharacterIDColumn, SessionKeyColumn, LogPathColumn, StartedAtColumn, LanguageColumn, LastByteOffsetColumn}
		mutableColumns       = sqlite.ColumnList{CharacterIDColumn, SessionKeyColumn, LogPathColumn, StartedAtColumn, LanguageColumn, LastByteOffsetColumn}
		defaultColumns       = sqlite.ColumnList{LanguageColumn, LastByteOffsetColumn}
	)

	return sessionsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		CharacterID:    CharacterIDColumn,
		SessionKey:     SessionKeyColumn,
		LogPath:        LogPathColumn,
		StartedAt:      StartedAtColumn,
		Language:       LanguageColumn,
		LastByteOffset: LastByteOffsetColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
