//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	CapEvents = CapEvents.FromSchema(schema)
	Characters = Characters.FromSchema(schema)
	CombatEvents = CombatEvents.FromSchema(schema)
	KillEvents = KillEvents.FromSchema(schema)
	MiningEvents = MiningEvents.FromSchema(schema)
	MiningFullEvents = MiningFullEvents.FromSchema(schema)
	ReloadEvents = ReloadEvents.FromSchema(schema)
	Sessions = Sessions.FromSchema(schema)
	TravelEvents = TravelEvents.FromSchema(schema)
}
