//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TravelEvents = newTravelEventsTable("", "travel_events", "")

type travelEventsTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnInteger
	SessionID  sqlite.ColumnInteger
	Timestamp  sqlite.ColumnTimestamp
	FromSystem sqlite.ColumnString
	ToSystem   sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TravelEventsTable struct {
	travelEventsTable

	EXCLUDED travelEventsTable
}

// AS creates new TravelEventsTable with assigned alias
func (a TravelEventsTable) AS(alias string) *TravelEventsTable {
	return newTravelEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TravelEventsTable with assigned schema name
func (a TravelEventsTable) FromSchema(schemaName string) *TravelEventsTable {
	return newTravelEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TravelEventsTable with assigned table prefix
func (a TravelEventsTable) WithPrefix(prefix string) *TravelEventsTable {
	return newTravelEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TravelEventsTable with assigned table suffix
func (a TravelEventsTable) WithSuffix(suffix string) *TravelEventsTable {
	return newTravelEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTravelEventsTable(schemaName, tableName, alias string) *TravelEventsTable {
	return &TravelEventsTable{
		travelEventsTable: newTravelEventsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newTravelEventsTableImpl("", "excluded", ""),
	}
}

func newTravelEventsTableImpl(schemaName, tableName, alias string) travelEventsTable {
	var (
		IDColumn         = sqlite.IntegerColumn("id")
		SessionIDColumn  = sqlite.IntegerColumn("session_id")
		TimestampColumn  = sqlite.TimestampColumn("timestamp")
		FromSystemColumn = sqlite.StringColumn("from_system")
		ToSystemColumn   = sqlite.StringColumn("to_system")
		allColumns       = sqlite.ColumnList{IDColumn, SessionIDColumn, TimestampColumn, FromSystemColumn, ToSystemColumn}
		mutableColumns   = sqlite.ColumnList{SessionIDColumn, TimestampColumn, FromSystemColumn, ToSystemColumn}
		defaultColumns   = sqlite.ColumnList{}
	)

	return travelEventsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		SessionID:  SessionIDColumn,
		Timestamp:  TimestampColumn,
		FromSystem: FromSystemColumn,
		ToSystem:   ToSystemColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
