//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CapEvents struct {
	ID           *int32 `sql:"primary_key"`
	SessionID    int32
	Timestamp    time.Time
	Module       string
	CapRequired  float32
	CapAvailable float32
}
