//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ReloadEvents struct {
	ID              *int32 `sql:"primary_key"`
	SessionID       int32
	Timestamp       time.Time
	Charge          string
	Launcher        string
	DurationSeconds int32
}
