//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Sessions struct {
	ID             *int32 `sql:"primary_key"`
	CharacterID    int32
	SessionKey     string
	LogPath        string
	StartedAt      time.Time
	Language       string
	LastByteOffset int32
}
